// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3fJwulK6dw94KaoRS_Ous7ZYJWtE_jC4',
    appId: '1:744340156786:web:03267b14932bfa8e23adeb',
    messagingSenderId: '744340156786',
    projectId: 'chatapp-73d98',
    authDomain: 'chatapp-73d98.firebaseapp.com',
    storageBucket: 'chatapp-73d98.appspot.com',
    measurementId: 'G-1YB704MR5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMg7iNOF11StL2oy-_z5zSAXHDDU49Sbk',
    appId: '1:744340156786:android:62594e2d1951620223adeb',
    messagingSenderId: '744340156786',
    projectId: 'chatapp-73d98',
    storageBucket: 'chatapp-73d98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6ZdSQIiN8L__IZMLXFc5f0Aej3f3dyqY',
    appId: '1:744340156786:ios:80b08f42de49689323adeb',
    messagingSenderId: '744340156786',
    projectId: 'chatapp-73d98',
    storageBucket: 'chatapp-73d98.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6ZdSQIiN8L__IZMLXFc5f0Aej3f3dyqY',
    appId: '1:744340156786:ios:0fab68d4ccdbe1fe23adeb',
    messagingSenderId: '744340156786',
    projectId: 'chatapp-73d98',
    storageBucket: 'chatapp-73d98.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
